name: Zbuduj APK (Android)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4

      - name: Skonfiguruj środowisko Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Skonfiguruj Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Wygeneruj brakujące pliki platformy Android
        working-directory: listaurodzin
        run: flutter create --platforms=android --org com.example .

      - name: Pobierz pakiety i zależności
        working-directory: listaurodzin
        run: flutter pub get

      - name: Zbuduj plik APK (Release)
        working-directory: listaurodzin
        run: flutter build apk --release --no-tree-shake-icons

      - name: Udostępnij gotowy plik APK do pobrania
        uses: actions/upload-artifact@v4
        with:
          name: lista-urodzin-apk
          path: listaurodzin/build/app/outputs/flutter-apk/app-release.apk
